# Generated by Django 2.2 on 2019-04-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name_plural': 'bonuses'},
        ),
    ]
